# NOTE: The env groups should be first created in the Render dashboard
# Since they do not allow `sync: false` in env groups, this is seems to be the only way

projects:
  - name: medusa-bff-test-project
    environments:
      - name: production
        services:
          - type: web
            runtime: image
            plan: free
            name: gateway-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: traefik/whoami:v1.11
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: free
            name: content-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: traefik/whoami:v1.11
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: free
            name: products-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: traefik/whoami:v1.11
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: free
            name: orders-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: traefik/whoami:v1.11
            envVars:
              - fromGroup: bff-prod-env-group

          - type: web
            runtime: image
            plan: free
            name: customers-prod
            region: oregon
            autoDeployTrigger: off
            image:
              url: traefik/whoami:v1.11
            envVars:
              - fromGroup: bff-prod-env-group