name: Deploy to Render

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets:
      RENDER_API_KEY:
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.app }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.app }}
    steps:
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_KEY: ${{ inputs.app }}
          IMAGE: ${{ inputs.image }}
        run: |
          service_data=$(
              curl -s "https://api.render.com/v1/services?name=$SERVICE_KEY&limit=1" \
                  -H "Authorization: Bearer $RENDER_API_KEY" \
                  -H "Accept: application/json" \
              | jq -r '.[0].service'
          )

          service_id=$(echo "$service_data" | jq -r '.id // empty')
          service_owner_id=$(echo "$service_data" | jq -r '.ownerId // empty')

          if [ -z "$service_id" ]; then
              echo "::error::Service not found: $SERVICE_KEY"
              exit 1
          fi

          updated=$(
              curl -s -X PATCH "https://api.render.com/v1/services/$service_id" \
                  -H "Authorization: Bearer $RENDER_API_KEY" \
                  -H "Accept: application/json" \
                  -H "Content-Type: application/json" \
                  -d "{ 
                          \"image\": { 
                              \"ownerId\": \"$service_owner_id\", 
                              \"imagePath\": \"$IMAGE\"
                          }
                      }" \
              | jq -r '.imagePath // empty'
          )

          if [ "$updated" != "$IMAGE" ]; then
              echo "::error::Failed to update service"
              exit 1
          fi

          dep_id=$(
              curl -s -X POST "https://api.render.com/v1/services/$service_id/deploys" \
                  -H "Authorization: Bearer $RENDER_API_KEY" \
                  -H "Content-Type: application/json" \
                  -d "{ \"imageUrl\": \"$IMAGE\" }" \
              | jq -r '.id // empty'
          )

          if [ -z "$dep_id" ]; then
              echo "::error::Deployment was not triggered"
              exit 1
          fi

          max_attempts=30
          sleep_seconds=30
          attempts=1

          while [ "$attempts" -le "$max_attempts" ]; do
              status=$(curl -s "https://api.render.com/v1/services/$service_id/deploys/$dep_id" \
              -H "Authorization: Bearer $RENDER_API_KEY" \
              -H "Accept: application/json" \
              | jq -r '.status // empty')

              echo "Attempt $attempts/$max_attempts: Status is '$status'"

              # created queued build_in_progress update_in_progress live deactivated build_failed 
              # update_failed canceled pre_deploy_in_progress pre_deploy_failed
              case "$status" in
                  "live")
                      echo "Deployment is live"
                      exit 0
                      ;;
                  "build_failed"|"update_failed"|"canceled"|"pre_deploy_failed")
                      echo "Deployment failed: $status"
                      exit 1
                      ;;
              esac

              attempts=$((attempts + 1))
              sleep "$sleep_seconds"
          done

          echo "::error::Deployment timed out"
          exit 1
